#!/usr/bin/env python
from message import Message
from ui import UI
import json

def main():
    f = open('eyes.json')
    eyes=json.load(f)
    f.close()
    m = Message.from_eyes(eyes, "east1")

    UI.program_header()
    m.display("lines")
    m.display("trigrams","ascii")

if __name__ == "__main__":
    main()